### ISSUE TITLE
Configuring .well-known/matrix/server

### ISSUE THREAD

**Issue by BackedUpBooty** [ArcticFoxes-net/Synapse-Docker-Compose#3]
hey, thanks for putting this guide together, it's the best I've seen so far. 

One thing that's catching me out is federation. You've written 
> Uncomment serve_server_wellknown to enable it and configure https://yourdoman.tld/.well-known/matrix/server for federation 
but I can't really figure out what this means. I've seen that there's a file called `server` which needs to include the m.server as `my.sub.domain:443` but I'm unsure where to put it.

Is there something I'm missing?

Cheers!

**Comment by tommytran732** [comment]
This is something you need to do on the webserver you use for your website. It is out of scope for the docker-compose stack.
